### ISSUE TITLE
Feature Request - Params File

### ISSUE THREAD

**Issue by cluedtke** [jhuckaby/wperf#5]
Big fan of this tool. Very handy and easy to use. Great work!

But is there a way to provide a separate params file, or can I request the feature be added?

**E.g.:**
```
wperf my-load-test.json --params params.json
```

_my-load-test.json:_
```json
{
  "url": "https://myserver.com/some/path?food=[food]"
}
```

_params.json:_
```json
{
  "food": ["apple", "orange", "banana"]
}
```
I know, for example, `jmeter` and `newman` treat this idea as "environments", which is what I would use it for .. when I have different `urls`, but same single-line _big_ `POST` `body`.  

_EDIT: after peaking at the docs and code more, `params` looks to be only used in the `url` portion (i.e. query params). Would still be great to be able to "template" and provide an environment file._

**Comment by jhuckaby** [comment]
Sure, this has been implemented in v1.0.4.  Thanks!
